# Site Settings
title: Navneeth Gokul
description: My personal website for my projects
url: "https://navneethgokul.github.io/"
github_username: navneeth3005

# Build settings
theme: jekyll-theme-minimal # A clean, default GitHub Pages theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from being processed by Jekyll
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
